name: CI for csgo-tracker

on:
  push:
    branches: [master]

jobs:
  build-electronapp:
    needs: [build-restapi, build-webapp]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install restapi dependencies
        run: cd restapi
        run: npm ci
        run: echo "${{secrets.RESTAPI_SECRETS}}" | Out-File secrets.js
      - name: Install webapp dependencies
        run: cd ..\webapp
        run: npm ci
      - name: Build webapp
        run: npm run build
      - name: Install electronapp dependencies
        run: cd ..\electronapp
        run: npm ci
        run: xcopy /s ..\webapp\dist resources
      - name: Build electronapp
        run: npm run dist
      - name: Upload electronapp
        run: Compress-Archive .\dist\ csgo-tracker.zip
        uses: actions/upload-artifact@v2
          with:
            name: csgo-tracker.zip
            path: csgo-tracker.zip
